javac server/Server.java ./common/*.java server/ImageProcessorImpl.java
javac server/ImageProcessorImpl.java ./common/*.java
rmic server.ImageProcessorImpl

javac client/Client.java
javac client/Page2.java